### PR TITLE
Improve dockerfile

### PR DESCRIPTION
**Pull request by kmb32123**
This significantly simplifies the dockerfile for stackedit by using [library/node](https://registry.hub.docker.com/u/library/node/) as its base.

This simplification works because `npm install` and `npm start` are called by the base image.

This will always create the container using the source code the dockerfile is "living with" and will not pull from git separately. Versioning is handled by specifying on dockerhub what git tagged versions should be made available.

To test I set up a [build repo on dockerhub](https://registry.hub.docker.com/u/library/node/) with several testing tags. If you wanted to set up an "official" stackedit build repo its pretty easy. Just setup the automatic builds as follows, where "Name" is the git tag to use code from and "Docker Tag Name" is the version name used by docker.

Type | Name | Dockerfile Location | Docker Tag Name
-------|---------|--------------------------|------------------------
Tag|master| / | latest
Tag|v4.3.2| / | v4.3.2
Tag|v4.3.1| / | v4.3.1

I believe this really is the best way to do this and should require virtually no future maintenance.

### CODE REVIEW

**Comment by SkypLabs** [comment]
It could be a good idea to add an official image on the [Docker Hub Registry][1].

By this way, an image peer release (tag) can be generated.

 [1]: https://registry.hub.docker.com/

**Comment by benweet** [comment]
Looks good to me. Could you upgrade to 0.12-onbuild?

**Comment by kmb32123** [comment]
Done. This will now target version 0.12.x of node.

Another option to take into consideration is targeting `0-onbuild` or  `onbuild` so that the Dockerbuilds always use the latest node; however, as you probably realize, this would require you to keep up with any possible breaking changes node makes in the future. Either way works for me.

**Comment by benweet** [comment]
Thx. Just setup a repo in Docker Hub to test that:
https://registry.hub.docker.com/u/benweet/stackedit/

**Comment by hacfi** [comment]
`bower install` seems to be missing so the image doesn’t work without running it in the container

**Pull request merged**
