### PR TITLE
Fix #213: remove gross lines from print

### LINKED ISSUE #213: Feature request - printing
If it's not too much of a hassle, it would be nice if there is a print button in the menu, so that one does not need to save the document as pdf and then print the pdf file.

### PR DESCRIPTION
**Pull request by Daniel-Hug**

### CODE REVIEW

**Comment by Daniel-Hug** [comment]
@benweet What's stopping this from being merged?

**Comment by benweet** [comment]
Sorry I didn't take care of this yet. How can I reproduce the problem?

**Comment by Daniel-Hug** [comment]
I see it in Chrome, not Firefox. Just hit <kbd>ctrl</kbd>+<kbd>P</kbd> on the editor page.
stackedit-gross-lines-in-print

**Comment by aioue** [comment]
+1

**Pull request merged**
