### PR TITLE
bump katex dependency, support new katex commands and unicode

### LINKED ISSUE #1335: Katex dependency update
Do you have any plan to update Katex dependency? Stackedit is currently using ver. 0.9.0alpha, but katex has been already released upto 0.10.0 or more.

### LINKED ISSUE #1337: Unicode characters in math
I have a whole lot of markdown documents that use the unicode "degree" symbol in math mode (rather than the horrible LaTeX workaround ^\circ). They used to render perfectly in Stackedit; but now every one of them gives KaTeX error such as

KaTeX parse error: Expected 'EOF', got '°' at position 7: i = 58°̲ 20′

Is there any way to fix this?

### LINKED ISSUE #1352: \tag Katex fails to render
This should render properly with Katex : ```\tag{hi} x+y^{2x}```
This is the example from the Katex doc : [https://khan.github.io/KaTeX/docs/supported.html#annotation](https://khan.github.io/KaTeX/docs/supported.html#annotation)

However, this simply cause this error in stackedit.io : 
```KaTeX parse error: Expected 'EOF', got '\tag' at position 1: \̲t̲a̲g̲{hi} x+y^{2x}```
The same message appears using ```$``` and ```$$``` for the equation.

Is there another way to tag equation if tag is not supported?

Thanks

### PR DESCRIPTION
**Pull request by flxwu**
Supporting  `\copyright`, `\textregistered,` `\textcircled`, `\tag` and much more

Resolves #1335 , resolves #1352 , resolves #1337 

See https://github.com/Khan/KaTeX/releases/tag/v0.10.0-alpha

### CODE REVIEW

**Comment by flxwu** [comment]
yep, doing right now 👍 @benweet  can I somehow contact you privately? On Twitter for example? 😊

**Comment by flxwu** [comment]
done @benweet

**Comment by benweet** [comment]
You can PM me on https://community.stackedit.io/u/benweet.

**Comment by flxwu** [comment]
How to do that? I cannot find any PM option on the profile 😬

**Pull request merged**
