### PR TITLE
Added Support for GFM Tasklist

### PR DESCRIPTION
**Pull request by jlogix**
### Added GFM task list support using:

markdown-it-task-lists (https://github.com/revin/markdown-it-task-lists)
turndown-plugin-gfm (https://github.com/domchristie/turndown-plugin-gfm)

### CODE REVIEW

**Comment by andybergon** [comment]
Really looking forward to this!

**Comment by benweet** [comment]
Using turndown to convert preview back to markdown is too destructive. Sorry.

**Comment by andybergon** [comment]
Will we see this feature implemented in another way?

**Comment by benweet** [comment]
@andybergon in v5.11.

**Pull request closed without merging**
